---
rancher_api_url: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') | default('', true) | regex_replace('/+$', '') }}"
rancher_validate_certs: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_VERIFY_SSL') | default('true', true) | bool }}"
rancher_cluster_id: c-n6thr
rancher_cluster_namespace: "{{ rancher_cluster_id }}"
rancher_downstream_api_url: "{{ rancher_api_url }}/k8s/clusters/{{ rancher_cluster_id }}"

rke2_target_version: ""
rke2_expected_node_count: 1
rke2_verify_release_tag: true

rke2_snapshot_operation_ttl_seconds: 86400
rke2_snapshot_timeout_seconds: 900
rke2_snapshot_poll_seconds: 5

rke2_upgrade_namespace: cattle-system
rke2_upgrade_plan_name: awx-rke2-server-upgrade
rke2_upgrade_service_account_name: awx-rke2-upgrader
rke2_upgrade_concurrency: 1
rke2_upgrade_timeout_seconds: 2400
rke2_upgrade_poll_seconds: 10
